### PR TITLE
local storage in contact form

### PR DESCRIPTION
**Pull request by mahdinoori2000**
### Added feature

- [ ]  Add local storage to the contact form:
-  when the user types in the input field of the contact section, data will save in local storage.
-  when the user refreshes the page, input field data will be preserved.

- [ ] **NOTE:**  I don't have partner  this week. The student success team is aware of this situation.
email screenshot

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
Hi @mahdinoori2000 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have commits from your partner, this is a collaboration milestone so it needs to have at least 1 commit from the other one as well

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by mahdinoori2000** [comment]
@GzimAsani As I mentioned in the description I don't have partner this week. The student success team is aware of this situation. They told me to finish the projects individually.

**Comment by GzimAsani** [comment]
> @GzimAsani As I mentioned in the description I don't have partner this week. The student success team is aware of this situation. They told me to finish the projects individually.

Please add the image of the conversation with the student success and ask for another code review

**Review by abdulhamiid — APPROVED** [review]
# Status: :green_circle:  Approved! :partying_face:
Hi @mahdinoori2000 👋, 

Your project is complete! Great job for nailing it right on the first attempt :1st_place_medal:. There is nothing else to say other than... it's time to merge it  :shipit:  Congratulations! :tada::100::star2:

giphy

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
